FROM moddevices/devtools:ub14-essential
MAINTAINER Alexandre Cunha <alex@moddevices.com>

# install python3.4 and python dev tools
RUN apt-get install -qy python3 python3-dev python3-all-dev python-pip python-virtualenv

CMD ["bash"]