FROM moddevices/devtools:ub18-essential
MAINTAINER Alexandre Cunha <ale@moddevices.com>

# install python3.4 and python dev tools
RUN apt-get install -qy python3 python3-dev python3-all-dev python3-pip python-virtualenv

CMD ["bash"]
