FROM moddevices/devtools:ub18-essential
MAINTAINER Alexandre Cunha <alex@moddevices.com>
ENV DEBIAN_FRONTEND noninteractive

# install python3.4 and python dev tools
RUN apt-get install -qy python3 python3-dev python3-all-dev python3-pip python-virtualenv

CMD ["bash"]
